#include "SDGString.h"
#include "Cutter.h"
#include "test_Tools.h"


CPPUNIT_TEST_SUITE_REGISTRATION(test_Tools);
//----------------------------------------------------------------------------------------------------------
void test_Tools::initTestSeq(void){

    //build fasta file with 1 seq
    const char *text1 = R""""(>test seq
ATATTTATTTTAGCGTTTACGCTATG)"""";
    std::ofstream fout("test1seq.fa");
    fout<<text1<<std::endl;
    fout.close();

    //build fasta file with 2 seq
    const char *text2 = R""""(>test seq1
ATATTTATTTTAGCGTTTACGCT
CAATCTTGTGCAAATGGCTGTGA
AG
>test seq2
GCAGTTTTGGATTTAAGTGAATG
CTTCCTCTGGTGACTTTAGTAAG
CCCCATTTT)"""";
    fout.open("test2seq.fa");
    fout<<text2<<std::endl;
    fout.close();
}
//----------------------------------------------------------------------------------------------------------
void test_Tools::cutterDB(void){

    std::string filename("testCutterDB.fa");
    const char *text_in = R""""(>seq1
AGTTACCATGCCCAGCATTAACCCCCCTCAACAACCACCTCCGCCTATGAAGCCCGCCCG
GTAGGCGACATCAGCAAAGTGCCAACGCTGTATATATATATATTGATCACGAGCTACCAT
GCCAGCATAGCCTCGTCCCCCGCTACCTGAAACTCTGTTGCACCCGATGATGAAATCGGC
ATGAACACACACACACACACATATTCACACATACTGCGTGGTGGCGACGCTCTCGACGTT
GAAATTAACATGAACCTACACACACACATACACACTGCGTAATCGCGACGTCCTCGTCTA
GACTCGCTATCTAGAACTAACGGGATCAAAAGCACTGCTGCTTGCCCGTGCGTATACATT
AAGAATAAAGCTTTCATCATTCTTGATCTTGACACCAAACCGAGCAGTTGATTTATTTAA
AGTGGCAAATATATATAACCTACATATATCATAAGTACACAATAAAGTCATTATTGACTC
ATG
>seq2
AGTTACCATGCCCAGCATTAACCCCCCTCAACAACCACCTCCGCCTATGAAGCCCGCCCG
GTAGGCGACATCAGCAAAGTGCCAACGCTGTATATATATATATTGATCACGAGCTACCAT
GCCAGCATAGCCNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNTGAAACTCTGTTGC
ATGAACACACACACACACACATATTCACACATACTGCGTGGTGGCGACGCTCTCGACGTT
GAAATTAACATGAACCTACACACACACATACACACTGCGTAATCGCGACGTCCTCGTCTA
GACTCGCTATCTAGAACTAACGGGATCAAAAGCACTGCTGCTTGCCCGTGCGTATACATT
AAGAATAAAGCTTTCATCATTCTTGATCTTGACACCAAACCGAGCAGTTGATTTATTTAA
AGTGGCAAATATATATAACCTACATATATCATAAGTACACAATAAAGTCATTATTGACTC
>seq3
>seq4

>seq5
AGTTACCATG
)"""";

    std::ofstream fout(filename);
    fout<<text_in<<std::endl;
    fout.close();

    const char *text_exp = R""""(>1  seq1 {Cut} 1..100
AGTTACCATGCCCAGCATTAACCCCCCTCAACAACCACCTCCGCCTATGAAGCCCGCCCG
GTAGGCGACATCAGCAAAGTGCCAACGCTGTATATATATA
>2  seq1 {Cut} 91..190
TATATATATATATTGATCACGAGCTACCATGCCAGCATAGCCTCGTCCCCCGCTACCTGA
AACTCTGTTGCACCCGATGATGAAATCGGCATGAACACAC
>3  seq1 {Cut} 181..280
ATGAACACACACACACACACATATTCACACATACTGCGTGGTGGCGACGCTCTCGACGTT
GAAATTAACATGAACCTACACACACACATACACACTGCGT
>4  seq1 {Cut} 271..370
CACACTGCGTAATCGCGACGTCCTCGTCTAGACTCGCTATCTAGAACTAACGGGATCAAA
AGCACTGCTGCTTGCCCGTGCGTATACATTAAGAATAAAG
>5  seq1 {Cut} 361..460
AAGAATAAAGCTTTCATCATTCTTGATCTTGACACCAAACCGAGCAGTTGATTTATTTAA
AGTGGCAAATATATATAACCTACATATATCATAAGTACAC
>6  seq1 {Cut} 451..483
ATAAGTACACAATAAAGTCATTATTGACTCATG
>7  seq2 {Cut} 1..100
AGTTACCATGCCCAGCATTAACCCCCCTCAACAACCACCTCCGCCTATGAAGCCCGCCCG
GTAGGCGACATCAGCAAAGTGCCAACGCTGTATATATATA
>8  seq2 {Cut} 91..132
TATATATATATATTGATCACGAGCTACCATGCCAGCATAGCC
>9  seq2 {Cut} 167..266
TGAAACTCTGTTGCATGAACACACACACACACACATATTCACACATACTGCGTGGTGGCG
ACGCTCTCGACGTTGAAATTAACATGAACCTACACACACA
>10  seq2 {Cut} 257..356
TACACACACACATACACACTGCGTAATCGCGACGTCCTCGTCTAGACTCGCTATCTAGAA
CTAACGGGATCAAAAGCACTGCTGCTTGCCCGTGCGTATA
>11  seq2 {Cut} 347..446
CGTGCGTATACATTAAGAATAAAGCTTTCATCATTCTTGATCTTGACACCAAACCGAGCA
GTTGATTTATTTAAAGTGGCAAATATATATAACCTACATA
>12  seq2 {Cut} 437..480
AACCTACATATATCATAAGTACACAATAAAGTCATTATTGACTC)"""";
    fout.open(filename+"_cut_exp");
    fout<<text_exp<<std::endl;
    fout.close();

    Cutter cutter;            //!< parameter of bank cut-out
    int verbose=1;
    cutter.setLength(100);
    cutter.setOver(10);
    cutter.setWord(11);
    if(!cutter.check(filename,verbose))
    {
        SDGString bqName=cutter.cutDB(filename,verbose);
        if(verbose>0)
            std::cout<<"\n\nbank '"<<bqName<<"' created!!\n";
    }
    std::ifstream t_exp(filename+"_cut_exp");
    std::stringstream buffer_exp;
    buffer_exp << t_exp.rdbuf();

    std::ifstream t_obs(filename+"_cut");
    std::stringstream buffer_obs;
    buffer_obs << t_obs.rdbuf();

    CPPUNIT_ASSERT_EQUAL(buffer_exp.str(),buffer_obs.str());
}
